# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-23 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends_app', '0002_auto_20171023_0424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='user',
        ),
        migrations.AddField(
            model_name='friend',
            name='users',
            field=models.ManyToManyField(to='friends_app.User'),
        ),
    ]
