# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-23 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends_app', '0003_auto_20171023_0435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='users',
        ),
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(related_name='_user_friends_+', to='friends_app.User'),
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
